package br.com.clyvo.pet.enums;

public enum TipoAlertaPreditivo {

    IMUNIZACAO_VENCIDA,
    IMUNIZACAO_PREVISTA,
    CHECKUP_PREVENTIVO,
    ACOMPANHAMENTO_CLINICO,
    REVISAO_MEDICAMENTOSA,
    ROTINA_CUIDADO,
    ALERTA_RISCO_SAUDE,
    MENSAGEM_RELACIONAMENTO,
    OUTRO
}